### ISSUE TITLE
How to convert OpenAPIv3 schema to .proto?

### ISSUE THREAD

**Issue by Ark-kun** [googleapis/gnostic#108]
I have an OpenAPIv3 schema or JsonSchema.
Can I use gnostic or gnostic-generate to produce equivalent .proto file?

```
openapi: 3.0.0
info:
  title: Sample API
  version: 0.1.9
paths:
  /pipeline_runs:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: https://raw.githubusercontent.com/kubeflow/pipelines/618b559391a225a6d821141047d6f7438e6f64a1/sdk/python/kfp/components/structures/components.json_schema.json#/definitions/TaskSpec
      responses:
        '200':
          description: Updated
```

**Comment by WilliamWhispell** [comment]
I've just started trying this out... wondering the same thing. I've tried on windows and linux, not seeing a proto file from the json input

**Comment by noahdietz** [comment]
`gnostic` does not yet convert OAS documents into `.proto` representations. But we have a summer project underway to explore this. Thanks for inquiring about this!

**Comment by LorenzHW** [comment]
Hello! As part of my [GSoC project](https://summerofcode.withgoogle.com/projects/#5244822191865856), I have the privilege to implement this feature under supervision from Tim and Noah. Currently, all the code is maintained [here](https://github.com/LorenzHW/gnostic-protoc-generator) and is in very active development. I'd say that the feature is in a pre-alpha release state and there is probably more that doesn't work than there is that does, but I welcome every kind of contribution (especially issues).

**Comment by timburks** [comment]
Just to follow up here, @LorenzHW's project is now at https://github.com/googleapis/gnostic-grpc. Thanks @LorenzHW !
