### ISSUE TITLE
Installation fails with undefined ExtensionHandlerRequest

### ISSUE THREAD

**Issue by jherrera123** [googleapis/gnostic#139]
First installation step fails with undefined ExtensionHandlerRequest

```bash
$ go get github.com/googleapis/gnostic
# github.com/googleapis/gnostic/extensions
go/src/github.com/googleapis/gnostic/extensions/extensions.go:39:14: undefined: ExtensionHandlerRequest
go/src/github.com/googleapis/gnostic/extensions/extensions.go:50:15: undefined: ExtensionHandlerResponse

$ go version
go version go1.12.7 linux/amd64
```

**Comment by giltohar** [comment]
I'm getting this too.

**Comment by noahdietz** [comment]
Please run `make build` from the root directory. The generated Go bindings were removed from the repo. 

If this fixes it for you, please close the issue. Thanks for reporting it!

@timburks if #138 is affecting the ability to install via Go tooling, we might want to revisit it.

**Comment by timburks** [comment]
https://github.com/googleapis/gnostic/pull/141 puts the generated files back in the repo.

We need to watch for problems if the generated code gets out of sync with the proto runtime.

**Comment by seh** [comment]
Can we reopen this issue? It's once again a problem with version 0.5.5.

**Comment by sloretz** [comment]
I was getting this error too using bzlmod. If you're using bzlmod and you need `proto_library` rules to use the `openapiv3` annotations, this seems to work for me with gnostic-models 0.7.0

1. Create a patch of https://github.com/google/gnostic-models/pull/23
2. Use `go_deps.module_override` to apply the patch, and `go_deps.gazelle_override` to massage everything else in your `MODULE.bazel`

```python
go_deps.module_override(
    patch_strip = 1,
    patches = [
        "//:gnostic-models-pr-23.patch",
    ],
    path = "github.com/google/gnostic-models",
)

go_deps.gazelle_override(
    directives = [
        "gazelle:proto default",
        "gazelle:go_generate_proto false",
        "gazelle:prefix github.com/google/gnostic-models",
    ],
    path = "github.com/google/gnostic-models",
)
```

3. Import `annotations.proto` in your proto file with:

```protobuf
import "openapiv3/annotations.proto";
```
