### ISSUE TITLE
Please create a v0.2.2 patch release

### ISSUE THREAD

**Issue by fejta** [googleapis/gnostic#147]
Will you push a `v0.2.2` tag? Feel free to make this the same commit as `v0.2.0`, but this is necessary in order to allow people to patch update this module correctly.

https://proxy.golang.org/github.com/googleapis/gnostic/@v/list shows that at some point you published a `v0.2.1`,

However this no longer appears in the list of https://github.com/googleapis/gnostic tags or branches. Furthermore, it looks like golang never actually downloaded v0.2.1. Compare the following:
* https://proxy.golang.org/github.com/googleapis/gnostic/@v/v0.2.0.info
* https://proxy.golang.org/github.com/googleapis/gnostic/@v/v0.2.1.info

Thus anyone attempting to patch release a repo that uses v0.2.0 will fail, see for example:
`go get -u=patch sig.k8s.io/controller-runtime`

See `go help goproxy` and https://proxy.golang.org/ for more info.

This will cause issues for people as go 1.13 will set `GOPROXY=https://proxy.golang.org GOSUMDB=sum.golang.org` by default.

**Comment by timburks** [comment]
https://github.com/googleapis/gnostic/tree/v0.2.2 is now available

**Comment by fejta** [comment]
Job failed but for a new reason, so I'm declaring success. Thanks!
