### ISSUE TITLE
module github.com/googleapis/gnostic@latest found (v0.4.1), but does not contain package github.com/googleapis/gnostic/OpenAPIv2

### ISSUE THREAD

**Issue by gh67uyyghj** [googleapis/gnostic#156]
The above error shows up when I try to get the latest k8s go client package.

**Comment by babinin** [comment]
Hi @gh67uyyghj 
as i see in v0.4.1 openapi is must be imported as
''openapi2 "github.com/googleapis/gnostic/openapiv2""
instead of previous
"openapiv2 "github.com/googleapis/gnostic/OpenAPIv2"".
it's pretty fresh release, so (i think) k8s client-go will be updated soon

**Comment by gh67uyyghj** [comment]
Thank you! I apologize it seems I should have opened it in the k8s go-client repo instead of here

**Comment by vvitayau** [comment]
still an issue
```
$ GO111MODULE=on go get -u github.com/go-acme/lego/v3/cmd/lego
go: downloading github.com/googleapis/gnostic v0.4.2
go: downloading k8s.io/utils v0.0.0-20200619165400-6e3d28b6ed19
go: finding module for package github.com/googleapis/gnostic/OpenAPIv2
go: finding module for package github.com/googleapis/gnostic/OpenAPIv2
go/pkg/mod/k8s.io/client-go@v11.0.0+incompatible/discovery/discovery_client.go:29:2: module github.com/googleapis/gnostic@latest found (v0.4.2), but does not contain package github.com/googleapis/gnostic/OpenAPIv2
```

**Comment by gabrielperezs** [comment]
I'm with the same issue, but maybe this helps to you: https://github.com/kubernetes/test-infra/issues/16116

`go get github.com/googleapis/gnostic@v0.4.0`

**Comment by nyetwurk** [comment]
```.go/pkg/mod/k8s.io/client-go@v0.17.11/discovery/discovery_client.go:29:2: module github.com/googleapis/gnostic@latest found (v0.5.1), but does not contain package github.com/googleapis/gnostic/OpenAPIv2```

```
        k8s.io/api v0.18.8
        k8s.io/apimachinery v0.18.8
        k8s.io/client-go v0.17.11
        k8s.io/utils v0.0.0-20200821003339-5e75c0163111 // indirect
```
```
	github.com/googleapis/gnostic v0.5.1 // indirect
```

**Comment by lboix** [comment]
Here is a workaround that could help, especially if you are using Kubernetes 1.14 : https://github.com/kubernetes/client-go/issues/741#issuecomment-807368949
