### ISSUE TITLE
Request for new version v0.4.2 or v0.5.0

### ISSUE THREAD

**Issue by RainbowMango** [googleapis/gnostic#170]
The struct type `InternalMessageInfo` has been deprecated by `github.com/golang/protobuf@v1.4.0`: 
https://github.com/golang/protobuf/blob/00998c7dd9d789e353c9518d13864b75cd23c55d/proto/deprecated.go#L85-L92

But the latest version(v0.4.1) of gnostic still refer to that deprecated `InternalMessageInfo`, such as:
https://github.com/googleapis/gnostic/blob/896953e6749863beec38e27029c804e88c3144b8/openapiv2/OpenAPIv2.pb.go#L4186

It seems the master version can fix that. So, what we need to do is cut a new release.

@timburks, How do you say?

**Comment by timburks** [comment]
Yes, seems like a good idea. Thanks for pointing this out!

**Comment by timburks** [comment]
Addressed in https://github.com/googleapis/gnostic/releases/tag/v0.4.2 - Thanks again for mentioning this!

**Comment by RainbowMango** [comment]
Thanks @timburks.
