### ISSUE TITLE
Multifile definition support

### ISSUE THREAD

**Issue by brindasanth** [googleapis/gnostic#193]
Hi Team,
How to generate Golang PROTO from open api spec definitions in multi file defined by path reference ?

Example : https://forge.etsi.org/rep/nfv/SOL005/tree/master/src/SOL005

It https://forge.etsi.org/rep/nfv/SOL005/blob/master/src/SOL005/NSLifecycleManagement/NSLifecycleManagement.yaml uses Definitions defined in https://forge.etsi.org/rep/nfv/SOL005/tree/master/src/SOL005/NSLifecycleManagement/definitions.

**Comment by timburks** [comment]
The gnostic tests include examples that read API specs that consist of multiple files [here's one](https://github.com/googleapis/gnostic/blob/ae26236156ff98d8de9d2bad34d4103b487b0a9a/gnostic_test.go#L106). The key is to directly read the top-level document and be sure that the specs that it references can be found by gnostic (usually with relative file path references).

**Comment by brindasanth** [comment]
Thanks  a lot @timburks
