### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by gchari-asapp** [googleapis/gnostic#204]
I am running on macos mojave and golang version 1.14.4.
Output after running make:
```
go generate ./...
go: found github.com/golang/protobuf/protoc-gen-go in github.com/golang/protobuf v1.4.2
go get ./...
go install ./...
cd extensions/sample; make
generate-gnostic --extension x-sampleone.json --out_dir=generated
make[1]: generate-gnostic: No such file or directory
make[1]: *** [build] Error 1
make: *** [all] Error 2
```

**Comment by timburks** [comment]
`go install ./...` should be compiling `generate-gnostic` and putting it in your `$GOPATH/bin` directory. Is `$GOPATH/bin` in your search path?

**Comment by gchari-asapp** [comment]
I think the problem is that `go install` is not generating anything. But there is not error message.
`$GOPATH` is not set so by default the bin should be inside the gnostic dir.
When I run `gnostic #v0.5.0 ❯ find ./ -name generate-gnostic` or `gnostic #v0.5.0 ❯ find ./ -name bin`
the output is empty.

**Comment by gchari-asapp** [comment]
Thanks!
