### ISSUE TITLE
Fix installation problems for openapi_go_client and other links

### ISSUE THREAD

**Issue by timburks** [googleapis/gnostic#27]
These links are currently installed into $(GOPATH):
`ln -s $(GOPATH)/bin/openapi_go_generator $(GOPATH)/bin/openapi_go_client`

But GOPATH can be a ":"-separated list of paths, and that breaks this process.

Instead modify the installation to link in the same directory that contains `openapi_go_generator`, which can be obtained as follows:

    GENERATOR = `which openapi_go_generator`
    GOBIN = `basepath $GENERATOR`
    ln -s $(GOBIN)/openapi_go_generator $(GOBIN)/openapi_go_client

**Comment by scottbla** [comment]
The "which" command works by iterating through $PATH, not $GOPATH...I'm not sure of the context for this problem, but maybe you need your own command to use $GOPATH?  And on my linux host, I see no "basepath" command -- I think you want "dirname" instead...so in this vein:

GENERATOR=`PATH=$GOPATH:$PATH which openapi_go_generator`
GOBIN=`dirname $GENERATOR`
ln -s $GOBIN/openapi_go_generator $GOBIN/openapi_go_client
# or...
# (cd $GOBIN && ln -s open_go_generator openapi_go_client)

You don't really need the full path in the symlink...it will be interpreted relative to the containing directory.

**Comment by timburks** [comment]
openapi_go_generator is no longer included with this project
