### ISSUE TITLE
Report errors by line number in source documents.

### ISSUE THREAD

**Issue by timburks** [googleapis/gnostic#31]
Currently errors are reported in terms of key paths in the source documents. It would be helpful to users to have this reflected back to line numbers.

**Comment by MikeRalphson** [comment]
Perhaps there is a go equivalent of [this](https://github.com/epoberezkin/json-source-map) library, or it could be ported?

**Comment by timburks** [comment]
It appears that the [yaml.v3](https://ubuntu.com/blog/api-v3-of-the-yaml-package-for-go-is-available) [Node](https://godoc.org/gopkg.in/yaml.v3#Node) will give us line numbers. Thanks @gizzon for the find!

**Comment by timburks** [comment]
Fixed in #219
