### ISSUE TITLE
Draft OpenAPI 3 schema issues

### ISSUE THREAD

**Issue by MikeRalphson** [googleapis/gnostic#35]
I believe these are all issues with the generated schema:

#### The definition of `requestBody` is an array of `requestBodyOrReference` - it should be a Map of Content Objects.

```diff
         "requestBody": {
-          "type": "array",
-          "items": {
-            "$ref": "#/definitions/requestBodyOrReference"
-          },
-          "uniqueItems": true
+          "type": "object",
+          "properties": {
+              "content": {
+                  "$ref": "#/definitions/content"
+              }
+          }
```

#### The definition of a `content` Object has `additionalProperties` of `mediaType` but should be a Map of `mediaType`s.

```diff
     "content": {
       "type": "object",
       "description": "Describes a set of supported media types. A Content Object can be used in Request Body Object, Parameter Objects, Header Objects, and Response Objects.  Each key in the Content Object is the media type of the Media Type Object.",
-      "additionalProperties": {
-        "$ref": "#/definitions/mediaType"
+      "patternProperties": {
+        ".*": {
+          "$ref": "#/definitions/mediaType"
+        }
       }
     },
```

#### `mediaType` is missing `description` property.

```diff
     "mediaType": {
       "type": "object",
       "description": "Each Media Type Object provides schema and examples for a the media type identified by its key.  Media Type Objects can be used in a Content Object.",
       "patternProperties": {
         "^x-": {
           "$ref": "#/definitions/specificationExtension"
         }
       },
       "properties": {
+        "description": {
+            "type": "string"
+        },
         "schema": {
           "$ref": "#/definitions/schemaOrReference"
         },
```

#### Remove property `$ref` from schema, already handled

```diff
           "$ref": "http://json-schema.org/draft-04/schema#/properties/enum"
         },
-        "$ref": {
-          "type": "string"
-        },
         "type": {
           "type": "string"
         },
```

#### `securityScheme` remove properties from `required` when they only have selective validity.

````diff
     "securityScheme": {
       "type": "object",
       "description": "Allows the definition of a security scheme that can be used by the operations. Supported schemes are HTTP authentication, an API key (either as a header or as a query parameter) and OAuth2's common flows (implicit, password, application and access code).",
       "required": [
-        "type",
-        "name",
-        "in",
-        "scheme",
-        "flow",
-        "openIdConnectUrl"
+        "type"
       ],
````

#### Same for `oauthFlow`

````diff
     "oauthFlow": {
       "type": "object",
       "description": "Configuration details for a supported OAuth Flow",
       "required": [
-        "authorizationUrl",
-        "tokenUrl",
         "scopes"
       ],
````

#### `schemaOrReference` had to change this to `anyOf` I think because `schema` itself contains `$ref`

````diff
     "schemaOrReference": {
-      "oneOf": [
+      "anyOf": [
         {
           "$ref": "#/definitions/schema"
         },
         {
           "$ref": "#/definitions/reference"
         }
       ]
````
#### `any` remove `type: object`, should match primitives etc

````diff
     "any": {
-      "type": "object",
       "additionalProperties": true,
       "additionalItems": true
     },
````

#### `specificationExtension` remove `type: object`, allow primitive types

````diff
     "specificationExtension": {
-      "type": "object",
+      "oneOf": [
+        {
+          "type": "integer"
+        },
+        {
+          "type": "number"
+        },
+        {
+          "type": "boolean"
+        },
+        {
+          "type": "string"
+        },
+        {
+          "type": "object"
+        },
+        {
+          "type": "array"
+        }
+      ],
````

Please let me know if you want me to annotate them against sections of the spec. I made these changes validating the output of a 2-to-3 converter, so there may be bugs in it, or in my reading of the spec.

Thanks, Mike

**Comment by timburks** [comment]
Thanks! I'll review all this.

**Comment by timburks** [comment]
[Here](https://gist.github.com/timburks/e6de7dc13681fb22c487a552352c2b7e) is a revised schema with some of the changes you listed. 

I've put comments on everything below. For some items, I think we may need changes to the specification text.


1. The definition of requestBody is an array of requestBodyOrReference - it should be a Map of Content Objects.

- [This](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#operation-object) suggests otherwise. Could that be incorrect?

2. The definition of a content Object has additionalProperties of mediaType but should be a Map of mediaTypes.

- Done.

3. Media type is missing a description property.

- The description property is not mentioned [here in the spec](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#media-type-object). Should it be added there?

4. Remove "$ref" from schema, already handled

- Done.

5. securityScheme remove properties from required when they only have selective validity.

- I was using the annotations in [this table](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#securitySchemeObject). Should they be changed?

6. Same for oauthFlow

- Similar to the previous point: [this table](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#oauthFlowObject) has "Required" annotations. Should those be changed in the spec?

7. schemaOrReference had to change this to anyOf I think because schema itself contains $ref

- I think this might not be necessary now that $ref is removed from Schema.

8. any remove type: object, should match primitives etc

- Done.

9. specificationExtension remove type: object, allow primitive types

- Done.

**Comment by MikeRalphson** [comment]
1. I think the array markers around the requestBody in the spec are a mistake. You are right the requestBody is an object in it's own right.

3. This looks like a bug in my converter, thanks!

5. The `required` annotation must be read in context of the `validity` column. I'm not sure JSON Schema Draft 4 can express co-dependencies, maybe Draft 5 [can](http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.19)?

6. As 5.

7. Will revalidate.

**Comment by timburks** [comment]
Agreed on 5 and 6. I'll ignore any "Required" fields that don't have "Any" validity.

**Comment by MikeRalphson** [comment]
1. Has been fixed in the spec.

**Comment by timburks** [comment]
[Here's an updated schema](https://github.com/googleapis/gnostic/blob/ea7ad4702156b729585d7dce21b75f678f61e84e/OpenAPIv3/openapi-3.0.json) that I believe addresses everything that we've discussed here. I'll merge it to master tomorrow unless you find any problems. Thanks!

**Comment by MikeRalphson** [comment]
The only issue that still seems to be remaining is `schemaOrReference` matching **both** `schema` and `reference` because `schema` itself includes a `$ref` property.

```diff
--- gnostic_original.json       2017-04-04 08:27:11.892586200 +0100
+++ openapi-3.json      2017-04-04 08:29:53.159450400 +0100
@@ -1084,7 +1084,7 @@
       ]
     },
     "schemaOrReference": {
-      "oneOf": [
+      "anyOf": [
         {
           "$ref": "#/definitions/schema"
         },
```

Changing from `oneOf` to `anyOf` fixes this in a non-intrusive way.

**Comment by timburks** [comment]
I thought we removed `$ref` from `schema` and I don't see it in the schema that I linked. Are you validating using the `schema` definition in that document? I'm confused as to why both are matching.

**Comment by MikeRalphson** [comment]
> I thought we removed $ref from schema and I don't see it in the schema that I linked. Are you validating using the schema definition in that document? I'm confused as to why both are matching.

You're right. I think it's matching both because they both allow additionalProperties?

The Reference Object should allow additionalProperties, even though they are [ignored](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#reference-object), so I've attempted to make the Schema Object **not** take additionalProperties.

This has meant defining (of all things) `additionalProperties` and `default` as properties of `schema`.

I've added a `defaultType` which includes `number`, `string`, `boolean`, `object` and `array` but **omits** `integer` as the `oneOf` causes problems with `defaults` like `1` which match both `integer` and `number` - there's probably a better way to express that with a `oneOf` containing an `anyOf` for integer|number.

I guess we haven't hit the problem in things like `specificationExtension` as people wouldn't tend to use integer or number types for those.

````diff
--- gnostic_original.json       2017-04-04 08:27:11.892586200 +0100
+++ openapi-3.json      2017-04-04 20:52:36.638336500 +0100
@@ -737,6 +737,7 @@
           "$ref": "#/definitions/specificationExtension"
         }
       },
+         "additionalProperties": false,
       "properties": {
         "nullable": {
           "type": "boolean"
@@ -857,9 +858,22 @@
         "properties": {
           "type": "object",
           "additionalProperties": {
-            "$ref": "#/definitions/schema"
+            "$ref": "#/definitions/schemaOrReference"
           }
         },
+               "additionalProperties": {
+                       "oneOf": [
+                               {
+                                       "$ref": "#/definitions/schemaOrReference"
+                               },
+                               {
+                                       "type": "boolean"
+                               }
+                       ]
+               },
+               "default": {
+                 "$ref": "#/definitions/defaultType"
+               },
         "description": {
           "type": "string"
         },
@@ -1108,7 +1122,7 @@
     "schemas": {
       "type": "object",
       "additionalProperties": {
-        "$ref": "#/definitions/schema"
+        "$ref": "#/definitions/schemaOrReference"
       }
     },
     "securitySchemes": {
@@ -1154,6 +1168,25 @@
         }
       ]
     },
+    "defaultType": {
+      "oneOf": [
+        {
+          "type": "array"
+        },
+        {
+          "type": "object"
+        },
+        {
+          "type": "number"
+        },
+        {
+          "type": "boolean"
+        },
+        {
+          "type": "string"
+        }
+      ]
+       },
     "primitive": {
       "oneOf": [
         {
````

**Comment by MikeRalphson** [comment]
> I guess we haven't hit the problem in things like specificationExtension as people wouldn't tend to use integer or number types for those.

Just found one! Same issue `oneOf` is matching both `integer` and `number`.

**Comment by MikeRalphson** [comment]
Just keeping track of issues as I spot them, the `defaultType` (or whatever we call it) `oneOf` array also needs to include `null`.

**Comment by MikeRalphson** [comment]
Current diff looks like this:

````diff
--- gnostic_original.json	2017-04-04 08:27:11.892586200 +0100
+++ openapi-3.json	2017-04-05 18:10:04.736413300 +0100
@@ -437,6 +437,7 @@
           "$ref": "#/definitions/specificationExtension"
         }
       },
+	  "additionalProperties": false,
       "properties": {
         "description": {
           "type": "string"
@@ -737,6 +738,7 @@
           "$ref": "#/definitions/specificationExtension"
         }
       },
+      "additionalProperties": false,
       "properties": {
         "nullable": {
           "type": "boolean"
@@ -857,9 +859,22 @@
         "properties": {
           "type": "object",
           "additionalProperties": {
-            "$ref": "#/definitions/schema"
+            "$ref": "#/definitions/schemaOrReference"
           }
         },
+        "additionalProperties": {
+            "oneOf": [
+                {
+                    "$ref": "#/definitions/schemaOrReference"
+                },
+                {
+                    "type": "boolean"
+                }
+            ]
+        },
+        "default": {
+          "$ref": "#/definitions/defaultType"
+        },
         "description": {
           "type": "string"
         },
@@ -1108,7 +1123,7 @@
     "schemas": {
       "type": "object",
       "additionalProperties": {
-        "$ref": "#/definitions/schema"
+        "$ref": "#/definitions/schemaOrReference"
       }
     },
     "securitySchemes": {
@@ -1135,7 +1150,7 @@
       "description": "Any property starting with x- is valid.",
       "oneOf": [
         {
-          "type": "integer"
+          "type": "null"
         },
         {
           "type": "number"
@@ -1154,12 +1169,31 @@
         }
       ]
     },
-    "primitive": {
+    "defaultType": {
       "oneOf": [
         {
-          "type": "integer"
+          "type": "null"
+        },
+        {
+          "type": "array"
+        },
+        {
+          "type": "object"
+        },
+        {
+          "type": "number"
+        },
+        {
+          "type": "boolean"
         },
         {
+          "type": "string"
+        }
+      ]
+    },
+    "primitive": {
+      "oneOf": [
+        {
           "type": "number"
         },
         {
````

This modified schema has been used to validate the output of an [OpenAPI 2 to 3 converter](https://github.com/mermade/swagger2openapi), and has been run over 36,035 valid OpenAPI 2 definitions (corpus contains duplicates).

**Comment by timburks** [comment]
@MikeRalphson, is [this](https://github.com/Mermade/swagger2openapi/blob/master/schemas/openapi-3.json) your latest revision of the schema?

**Comment by MikeRalphson** [comment]
Hi @timburks yes, that's the latest I have.

**Comment by timburks** [comment]
@MikeRalphson I'm generating a new version from 3.0.0-rc2 and comparing it with your version. I notice a few differences that seem to be due to changes in the spec:
* In the `serverVariable` object, the `enum->items` and `default` types are now `string` instead of `primitive`.
* In `pathItem` and `operation`, the `servers` property is now an array.
* there's a new `allowReserved` property on the `encodingProperty` object.
* plus a few other things related to examples that I'm still sorting out.

Also, It appears that you added `"additionalProperties": false` to the `requestBody` and `schema` objects. Could you help me understand why that was necessary for these objects but not not others?

**Comment by MikeRalphson** [comment]
Hi @timburks yes, I think all those differences are recent changes to the spec. BTW RC2 is a pre-release work in progress, so it might be best to work from the RC1 **tag** (unless I'm behind the times).

> Also, It appears that you added "additionalProperties": false to the requestBody and schema objects. Could you help me understand why that was necessary for these objects but not not others?

I think I mentioned that above somewhere, because where we have `referenceOrSomething` and the `reference` object allows additional properties, if the `something` object **also** allows additional properties, then things match both `reference` and `something`, which causes problems with the `oneOf` constraint. No other objects caused problems valdating with this schema across my test corpuses.

I can take another look tomorrow and see if there's a reason it wasn't necessary anywhere else.

**Comment by timburks** [comment]
@MikeRalphson [Here](https://gist.github.com/timburks/e6de7dc13681fb22c487a552352c2b7e) is my latest auto-generated schema from RC2.

Please test this and let me know what problems you find. I haven't tried to generate code from this yet, but will do that soon. Apart from the version changes, it has a couple of minor differences from your version involving things that I haven't tried to automatically infer and didn't want to hard-code (please review a diff for details).

**Comment by timburks** [comment]
I've got generated code working with [this version](https://github.com/googleapis/gnostic/blob/openapi-v3.0.0-rc2/OpenAPIv3/openapi-3.0.json) (in the openapi-v3.0.0-rc2 branch)

**Comment by MikeRalphson** [comment]
* [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#schema-object) should have a `default` property. Added back in `defaultType`.
* [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#schema-object) should have an `additionalProperties` property which can be a `boolean` or `object`.

There are three empty `descriptions`, which you may already be aware of.

I'm also going to raise an issue/PR against the OAS for the following case:

* The [Components Object](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#componentsObject) `schemas` property is defined as a Map[`string`, [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#schemaObject)] but to allow for direct aliasing of one schema to another, or external references, this needs to be a Map[`string`, [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#schemaObject) | [Reference Object](https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.md#referenceObject)]

Latest modified schema [here](https://github.com/Mermade/swagger2openapi/blob/master/schemas/openapi-3.json). This passes my standard test cases, I'm just running against the huge github/swaggerhub corpus now.

Cheers, Mike

**Comment by timburks** [comment]
Looking good! This [new generated version](https://github.com/googleapis/gnostic/blob/openapi-v3.0.0-rc2/OpenAPIv3/openapi-3.0.json) differs only in indentation and the value of [definitions->schemas->additionalProperties->$ref](https://github.com/googleapis/gnostic/blob/master/OpenAPIv3/openapi-3.0.json#L1111), which will match when your PR is merged and run through the schema generator.

**Comment by timburks** [comment]
@MikeRalphson [This generated schema](https://github.com/googleapis/gnostic/blob/openapi-v3.0.0-rc2/OpenAPIv3/openapi-3.0.json) includes the changes in [your commit](https://github.com/OAI/OpenAPI-Specification/commit/34fd4155a60e6d94a84d781a99a8242a6dd41046).

**Comment by MikeRalphson** [comment]
@timburks passes my standard test-cases, just running on the github/swaggerhub corpus now.

**Comment by timburks** [comment]
@MikeRalphson Thanks for all your guidance on this. I'll close this and we deal with other changes issue-by-issue, such as [this PR](https://github.com/googleapis/gnostic/pull/38).

**Comment by KES777** [comment]
> #### `specificationExtension` remove `type: object`, allow primitive types
> 
> ```diff
>      "specificationExtension": {
> -      "type": "object",
> +      "oneOf": [
> +        {
> +          "type": "integer"
> +        },
> +        {
> +          "type": "number"
> +        },
> +        {
> +          "type": "boolean"
> +        },
> +        {
> +          "type": "string"
> +        },
> +        {
> +          "type": "object"
> +        },
> +        {
> +          "type": "array"
> +        }
> +      ],
> ```
> 
> Please let me know if you want me to annotate them against sections of the spec. I made these changes validating the output of a 2-to-3 converter, so there may be bugs in it, or in my reading of the spec.
> 
> Thanks, Mike

Hello, Mike. Should it be `anyOf` instead of `oneOf`? In my case `x-my-prop: 1` matched as number and as string and whole validation fails.

**Comment by MikeRalphson** [comment]
Hmm, are you using JSON or YAML? An unquoted number should not match as a string in either...

**Comment by KES777** [comment]
YAML
