### ISSUE TITLE
OpenAPI 3.0.x schema - use of additionalItems

### ISSUE THREAD

**Issue by MikeRalphson** [googleapis/gnostic#39]
From the JSON schema draft 4 validation [document](https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.3.1):

> Successful validation of an array instance with regards to these two
   keywords is determined as follows:

>  if "items" is not present, or its value is an object, validation
   of the instance always succeeds, regardless of the value of
   "additionalItems";

Therefore is the use of `additionalItems: true` achieving anything? I ask because I'm trying determine how close we are to an OpenAPI-described API being able to serve its own OpenAPI definition via a schema-defined response.

**Comment by timburks** [comment]
I'm not attached to these properties and their values. I believe they are carried over from the 2.0 schema ("vendorExtension" definition). If you think it's best, I'll stop adding them to the "object", "any", and "expression" definitions.

**Comment by timburks** [comment]
Actually, your original statement is convincing enough. It's [out](https://github.com/googleapis/gnostic/commit/39a4144fd309362be6c9e8a3db101a0e2b7f62af).

**Comment by timburks** [comment]
@MikeRalphson I think I've addressed this. Reopen this if you think it needs more discussion.
