### ISSUE TITLE
Create release branches

### ISSUE THREAD

**Issue by mbohlool** [googleapis/gnostic#62]
We are using this repo's proto definitions of OpenAPI v2 in kubernetes. In MIME type, we reference this repo and it would be nice if we have a release branch to point instead of a hash.

https://github.com/kubernetes/kube-openapi/blob/c2fb93ef0d03d716a5a7d0df759d693b9ff2e07c/pkg/handler/handler.go#L48

An alternative would be moving proto files to a separate repo, something like [proto-openapi](https://github.com/proto-openapi/spec) in rhyme with [go-openapi](https://github.com/go-openapi/spec)?

**Comment by timburks** [comment]
Added beta release tag [v0.1.0](https://github.com/googleapis/gnostic/tree/v0.1.0).

**Comment by timburks** [comment]
Following up on the suggestion that @mbohlool made about an org:

I'd like to break the gnostic repo into multiple parts, particularly to get the Swift, Go, and future code generators in their own repos so they can be managed by appropriate people. To support the Kubernetes use, it makes sense to me to use separate repos for the OpenAPI models (protos + generated code) and possibly also the proto model that gnostic has for Discovery Format.

If the org is called `gnosticapis`, then the OpenAPI v2 models could be in `gnosticapis/openapiv2`,
and the Kubernetes MIME string might be:

`application/com.github.gnosticapis.openapiv2@v1.0+protobuf`

where `v1.0` is the release tag and `+protobuf` indicates type.
