### ISSUE TITLE
[gnostic-go-generator] Generate interface instead of struct for empty schema

### ISSUE THREAD

**Issue by sslavic** [googleapis/gnostic#73]
OpenAPI 3 supports empty schema (see https://swagger.io/docs/specification/data-models/data-types/#any)

Empty schema allows for flexibility - be strict in some parts of the schema/API while still allowing some properties to be of "any" type. E.g. for APIs which act as proxy, dumb pipe like PubSub kind of service, it's possible to produce flexible API, allowing message/event source and end consumer to agree on the data (message payload) schema (and just pass that info through), while same API could still have strict enforcing of some mandatory context/metadata information.

Currently gnostic-go-generator for an empty schema generates an empty struct type. IMO it should generate interface type instead.

By https://golang.org/pkg/encoding/json/#Marshal

> Struct values encode as JSON objects.

while

> Interface values encode as the value contained in the interface.

Similarly, by https://golang.org/pkg/encoding/json/#Unmarshal

> To unmarshal JSON into a struct, Unmarshal matches incoming object keys to the keys used by Marshal ...

while
> To unmarshal JSON into an interface value, Unmarshal stores one of these in the interface value:
```
bool, for JSON booleans
float64, for JSON numbers
string, for JSON strings
[]interface{}, for JSON arrays
map[string]interface{}, for JSON objects
nil for JSON null
```

If gnostic-go-generator would generate interface type instead of struct type for empty schema then e.g. in PubSub kind of API implementation JSON property of "any" type could be properly passed through (unmarshalled and marshalled) without losing data.

Current workaround is to manually change the type for AnyValue in generated code (types.go).

**Comment by sslavic** [comment]
As another (quick and dirty) workaround, it seems it's enough to change line https://github.com/googleapis/gnostic/blob/master/plugins/gnostic-go-generator/render_types.go#L30
with something like
```
			if len(modelType.Fields) > 0 {
				f.WriteLine(`type ` + modelType.TypeName + ` struct {`)
			} else {
				f.WriteLine(`type ` + modelType.TypeName + ` interface {`)
			}
```

Even with this workaround, it seems that `nullable` seems to be ignored, for all schemas, including `AnyValue` schema.

**Comment by timburks** [comment]
Thanks! A change to fix this was just merged to master.
