### ISSUE TITLE
[gnostic-go-generator] Generated names for non-200 responses do not compile

### ISSUE THREAD

**Issue by sslavic** [googleapis/gnostic#74]
As by https://swagger.io/docs/specification/describing-responses/

> An API specification needs to specify the responses for all API operations. Each operation must have at least one response defined, usually a successful response. A response is defined by its HTTP status code and the data returned in the response body and/or headers.

https://github.com/googleapis/gnostic/blob/master/plugins/gnostic-go-generator/language.go#L89 handles well only "200" response by using OK as field name. For all other responses, response code is being used as field name and since response codes are numbers they do not satisfy Go's requirement that variable names have to start with a letter. So `types.go` and `client.go` get generated with syntax errors.

**Comment by timburks** [comment]
Thanks for posting this. An update that addresses it was just merged to master.
