### ISSUE TITLE
Support for OAS 3.0.1

### ISSUE THREAD

**Issue by hyfather** [googleapis/gnostic#81]
Hi there! Since OAS 3.0.1 is [now published](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md), are there any plans to rev gnostic's current draft support of the spec?

**Comment by timburks** [comment]
Yes, definitely intent, though timing is unclear. Probably in the next month or so. Thanks for posting!

**Comment by soumyakantiroychowdhury** [comment]
+1

**Comment by timburks** [comment]
Please check [v0.2.0](https://github.com/googleapis/gnostic/releases/tag/v0.2.0) for a schema for OAS 3.0.1.
