### ISSUE TITLE
How should the compiler parse and represent extensions?

### ISSUE THREAD

**Issue by timburks** [googleapis/gnostic#9]
Currently extensions are represented with an internal "Any" type that stores them in the model as JSON. I've heard other ideas for this, including representing them as parsed protobufs defined by other schema.

**Comment by timburks** [comment]
We're currently storing extension values in YAML form in a field named "yaml".

**Comment by guptasu** [comment]
One possible approach can be this:

May be having a plugin model, all of the code for which is auto generated from the json schema of the extension. These plugins are invoked from the openapic as it encounters 'x-' extensions.

User workflow will be:
1. Extension owner provide a json schema for their extension to a generator code. Extensions plugin generators are invoked before invoking the openapic.
2. Using this json schema, the generator code will create a proto and compiler that can construct this proto from a json object. Similar to the code we have to OpenAPIV2 generator.
3. This extension compiler is responsible for taking in a YAML string and writing out a ByteString (all of this can be autogenerated via the generator and user just has to provide the json schema).
4. openapic code will have some sort of registration to know extension plugin to invoke for various extensions that it will encounter as it runs (or openapic might not care and invoke all extension plugins in a sequence and break if the input gets handled by any extension plugin). openapic will invoke the extension plugins (very similar to plugins you already have) ) and then stick the returned ByteString in the generated openAPI proto object as a google.protofuf.Any type.
5. The consumer of openAPI proto will detect the extensions they are interested in and will have to parse the Any type's ByteString back into the proto object that was created from the extensions json schema by the generator.

Hope that make sense.

**Comment by timburks** [comment]
Generally resolved by https://github.com/googleapis/gnostic/pull/32.
